import {Text} from 'react-native';

const messages = {
  audioMessage: {
    type: 'audio',
    audioURL: 'audio url',
    position: 'right',
    duration: 0,
    started: false,
    playIcon: <Text>pl</Text>,
    playState: 'paused',
    pauseIcon: <Text>pa</Text>,
    slider: <Text>slider</Text>,
    audioTime: <Text>15:03</Text>,
    onStartPlay: () => console.log('onstart'),
    onPausePlay: () => console.log('onpause'),
    onResumePlayer: () => console.log('onresume'),
  },
  fileMessage: {
    type: 'file',
    body: 'map',
    data: {
      size: 10,
      status: {click: false, loading: false, error: false, download: false},
    },
    downloadFile: () => console.log('download file'),
    downloadIcon: <Text>D</Text>,
    errorIcon: <Text>E</Text>,
    fileIcon: <Text>F</Text>,
    fileSizeConversion: () => '10',
    id: '1',
    onPress: () => console.log('on press'),
    openFile: () => console.log('open file'),
    position: 'right',
    progress: <Text>progress</Text>,
    onLongPress: () => console.log('select message'),
  },
  locationMessage: {
    type: 'location',
    locationURL: () =>
      'https://img.freepik.com/free-photo/abstract-grunge-decorative-relief-navy-blue-stucco-wall-texture-wide-angle-rough-colored-background_1258-28311.jpg?',
    onPress: () => console.log('on press'),
    onLongPress: () => console.log('select message'),
  },

  meetingMessage: {
    avatarIcon: <Text>AI</Text>,
    cancelSelect: () => console.log('cancel select'),
    dataSource: [],
    date: 'date',
    dateText: 'date',
    downloadFile: () => console.log('download file'),
    icon: <Text>I</Text>,
    onPressMeetingVideoLink: () => console.log('onPressMeetingVideoLink'),
    onPressTitle: () => console.log('onPressMeetingVideoLink'),
    onPressToggle: () => console.log('onPressMeetingVideoLink'),
    openFile: () => console.log('onPressMeetingVideoLink'),
    openImageViewer: () => console.log('onPressMeetingVideoLink'),
    reSendMessage: () => console.log('onPressMeetingVideoLink'),
    selectMessage: () => console.log('onPressMeetingVideoLink'),
    type: 'meeting',
    recordIcon: <Text>RI</Text>,
    subject: 'subject',
    title: 'title',
    toggleElement: <Text>TE</Text>,
    state: {participants: '', toggle: false},
  },
  meetingLinkMessage: {
    type: 'meetingLink',
    icon: <Text>icon</Text>,
    onPress: () => console.log('onpress'),
    title: 'kldnfve',
  },
  photoMessage: {
    type: 'photo',
    data: {
      status: {download: false, click: false, error: false, loading: false},
      uri: 'https://img.freepik.com/free-photo/abstract-grunge-decorative-relief-navy-blue-stucco-wall-texture-wide-angle-rough-colored-background_1258-28311.jpg?',
    },
    downloadFile: () => console.log('download file'),
    downloadIcon: <Text>D</Text>,
    errorIcon: <Text>E</Text>,
    id: '10',
    openMediaViewer: () => console.log('open media viewer'),
    progress: <Text>progress</Text>,
    onLongPress: () => console.log('select message'),
  },
  replyMessage: {
    type: 'reply',
    closeButton: true,
    closeButtonIcon: <Text>CB</Text>,
    photoURL: require('../assets/download.png'),
    onLongPress: () => console.log('select message'),
    message: () => 'message',
    title: 'title',
    titleColor: 'red',
  },
  systemMessage: {
    type: 'system',
    date: () => '29 ağu pazartesi',
  },
  textMessage: {
    type: 'text',
    messageBody: () => <Text>wkndjk</Text>,
    body: 'kwefjkwn',
  },
  videoMessage: {
    type: 'video',
    onPress: () => console.log('download file'),
    downloadIcon: <Text>DI</Text>,
    errorIcon: <Text>EI</Text>,
    message: {
      data: {
        thumbnailURL: require('../assets/kedi.mp4'),
        status: {
          click: false,
          loading: false,
          error: false,
          download: false,
        },
      },
      body: 'kedi.mp4',
    },
    onPressFile: () => console.log('on press file'),
    progress: <Text>P</Text>,
    onLongPress: () => console.log('select message'),
    videoPlayIcon: <Text>VPI</Text>,
  },
};

export default messages;
