import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  // ListItem Style Templates
  listItemContainer: {
    minHeight: 70,
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginRight: 10,
    marginLeft: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 0.5,
    borderBottomColor: '#d8d5d5',
    paddingTop: 10,
    paddingBottom: 10,
  },
  userImageArea: {
    width: 50,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 3,
  },
  userImageStatus: {
    width: 65,
    height: 65,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    borderStyle: 'solid',
    borderWidth: 3,
    borderRadius: 100,
    marginLeft: 3,
  },
  userNavbarImageArea: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginLeft: 45,
    marginRight: 45,
  },
  userChatImage: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  userImage: {
    width: 60,
    height: 60,
    borderWidth: 3,
    borderRadius: 100,
    borderColor: '#fff',
  },
  userDetailArea: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'center',
    paddingLeft: 10,
  },
  userDetailItems: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  userName: {
    color: '#3e3e3e',
    fontSize: 17,
    paddingBottom: 5,
  },
  userStatusArea: {
    height: 16,
    width: 16,
    position: 'absolute',
    bottom: -5,
    right: 3,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  groupUserStatusArea: {
    height: 15,
    width: 15,
    position: 'absolute',
    bottom: 2,
    right: 5,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#fff',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  chatPlatformIcon: {
    alignSelf: 'center',
  },
  groupUserName: {
    color: '#37748d',
    fontSize: 13,
    paddingRight: 10,
  },

  messageCount: {
    height: 20,
    width: 20,
    backgroundColor: '#ff5c5c',
    borderRadius: 10,
    flexDirection: 'column',
    alignItems: 'center',
    marginLeft: 5,
    justifyContent: 'center',
  },
  messageCountText: {
    color: '#fff',
    backgroundColor: 'transparent',
    fontSize: 12,
  },
  chatMessage: {
    color: '#555',
    fontSize: 15,
    paddingTop: 1,
  },
});

export default styles;
